package com.zerren.zedeng.handler;

import com.zerren.zedeng.reference.Reference;
import cpw.mods.fml.client.event.ConfigChangedEvent;
import cpw.mods.fml.common.eventhandler.SubscribeEvent;
import net.minecraftforge.common.config.Configuration;

import java.io.File;

/**
 * Created by Zerren on 2/19/2015.
 */
public class ConfigHandler {

    public static Configuration config;

    public static boolean devDebug;
    public static float vaultResistance;
    public static boolean bedrockVault;
    public static int vaultPages;
    public static float steamFactor;
    public static boolean uniSteam;
    public static boolean harderStainless;

    public static double packetRange = 64D;

    public static int[] potionIDs = {66, 67, 68, 69, 70};


    public static void init(File configFile){

        if (config == null) {
            config = new Configuration(configFile);
            loadConfig();
        }
    }

    private static void loadConfig() {
        potionIDs = config.get("potionIDs", "potionIDs", potionIDs, "Potion ID array in descending order (A, B, G, N, Rad S.)", 33, 127).getIntList();

        devDebug = config.getBoolean("devDebug", "general", false, "System print for debugging--leave false unless you have a log spam fetish");

        vaultResistance = config.getFloat("vaultResistance", "general", 100F, 10F, 600F, "Blast resistance of a player owned and locked vault");
        bedrockVault = config.getBoolean("bedrockVault", "general", false, "If true, player owned and locked vaults are 100% immune to explosions--overwrites vaultResistance");
        vaultPages = config.getInt("vaultPages", "general", 10, 1, 20, "How many pages of 54 slots the vault will have. (1 page = double chest, default is 540 slots)");

        harderStainless = config.getBoolean("harderStainless", "general", false, "If true, the recipe for stainless steel dust requires steel dust in place of iron dust. For use with mods that add steel dust");

        uniSteam = config.getBoolean("uniSteam", "general", false, "If true, this mod will produce/consume steam that can be used/generated by other mods (Railcraft, TE). Not balanced.");
        steamFactor = config.getFloat("steamFactor", "general", 1F, 0.1F, 5F, "Multiplier on steam produced--(this is always a 1:160 water:steam ratio though)--best if used with 'uniSteam'");

        packetRange = config.get("general", "packetRange", 128D, "Range (in blocks) that tile entity packets will be sent. Higher increases network load", 32D, 4096D).getDouble();

        if (config.hasChanged()) {
            config.save();
        }
    }

    @SubscribeEvent
    public void onConfigurationChangedEvent(ConfigChangedEvent.OnConfigChangedEvent event) {
        if (event.modID.equalsIgnoreCase(Reference.ModInfo.MOD_ID)) {
            loadConfig();
        }
    }
}
